-- Warehouses, per-warehouse stock, document warehouse_id, stock_movements.warehouse_id

-- -----------------------------------------------------------------------------
-- warehouses (numeric id; id = 1 reserved for system default)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.warehouses (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  location text,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS warehouses_at_most_one_default
  ON public.warehouses (is_default)
  WHERE is_default;

INSERT INTO public.warehouses (id, name, location, is_default)
VALUES (1, 'default', NULL, true)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.warehouses', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.warehouses), 1)
);

-- -----------------------------------------------------------------------------
-- product_warehouse_stock (authoritative per-location qty; products.quantity = sum)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.product_warehouse_stock (
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  warehouse_id bigint NOT NULL REFERENCES public.warehouses(id) ON DELETE RESTRICT,
  quantity integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, warehouse_id),
  CONSTRAINT product_warehouse_stock_quantity_non_negative CHECK (quantity >= 0)
);

INSERT INTO public.product_warehouse_stock (product_id, warehouse_id, quantity)
SELECT id, 1, quantity FROM public.products
ON CONFLICT (product_id, warehouse_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.sync_product_quantity_from_warehouse_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  pid uuid;
BEGIN
  pid := COALESCE(NEW.product_id, OLD.product_id);
  UPDATE public.products p
  SET
    quantity = COALESCE((
      SELECT SUM(s.quantity)::integer
      FROM public.product_warehouse_stock s
      WHERE s.product_id = pid
    ), 0),
    updated_at = now()
  WHERE p.id = pid;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_pws_sync_product_qty ON public.product_warehouse_stock;
CREATE TRIGGER trg_pws_sync_product_qty
  AFTER INSERT OR UPDATE OR DELETE ON public.product_warehouse_stock
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_product_quantity_from_warehouse_stock();

CREATE OR REPLACE FUNCTION public.on_product_insert_default_warehouse_stock()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO public.product_warehouse_stock (product_id, warehouse_id, quantity)
  VALUES (NEW.id, 1, COALESCE(NEW.quantity, 0));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_product_insert_pws ON public.products;
CREATE TRIGGER trg_product_insert_pws
  AFTER INSERT ON public.products
  FOR EACH ROW
  EXECUTE FUNCTION public.on_product_insert_default_warehouse_stock();

-- One-time: align products.quantity with sums (redundant if backfill matched)
UPDATE public.products p
SET quantity = COALESCE((
  SELECT SUM(s.quantity)::integer
  FROM public.product_warehouse_stock s
  WHERE s.product_id = p.id
), 0),
updated_at = now();

-- -----------------------------------------------------------------------------
-- stock_movements.warehouse_id
-- -----------------------------------------------------------------------------
ALTER TABLE public.stock_movements
  ADD COLUMN IF NOT EXISTS warehouse_id bigint REFERENCES public.warehouses(id);

UPDATE public.stock_movements SET warehouse_id = 1 WHERE warehouse_id IS NULL;
ALTER TABLE public.stock_movements ALTER COLUMN warehouse_id SET DEFAULT 1;
ALTER TABLE public.stock_movements ALTER COLUMN warehouse_id SET NOT NULL;

-- -----------------------------------------------------------------------------
-- purchase_orders.warehouse_id
-- -----------------------------------------------------------------------------
ALTER TABLE public.purchase_orders
  ADD COLUMN IF NOT EXISTS warehouse_id bigint REFERENCES public.warehouses(id);

UPDATE public.purchase_orders SET warehouse_id = 1 WHERE warehouse_id IS NULL;
ALTER TABLE public.purchase_orders ALTER COLUMN warehouse_id SET DEFAULT 1;
ALTER TABLE public.purchase_orders ALTER COLUMN warehouse_id SET NOT NULL;

-- -----------------------------------------------------------------------------
-- orders.warehouse_id
-- -----------------------------------------------------------------------------
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS warehouse_id bigint REFERENCES public.warehouses(id);

UPDATE public.orders SET warehouse_id = 1 WHERE warehouse_id IS NULL;
ALTER TABLE public.orders ALTER COLUMN warehouse_id SET DEFAULT 1;
ALTER TABLE public.orders ALTER COLUMN warehouse_id SET NOT NULL;

-- -----------------------------------------------------------------------------
-- RLS (match existing permissive pattern)
-- -----------------------------------------------------------------------------
ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_warehouse_stock ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for now" ON public.warehouses
  FOR ALL TO public USING (true) WITH CHECK (true);

CREATE POLICY "Allow all for now" ON public.product_warehouse_stock
  FOR ALL TO public USING (true) WITH CHECK (true);

-- Keep identity sequence past manually inserted ids (app calls after create with explicit id).
CREATE OR REPLACE FUNCTION public.refresh_warehouse_id_sequence()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM setval(
    pg_get_serial_sequence('public.warehouses', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.warehouses), 1)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.refresh_warehouse_id_sequence() TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_warehouse_id_sequence() TO authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_warehouse_id_sequence() TO service_role;
